spring.application.name=nail_first

spring.datasource.url=jdbc:postgresql://localhost:5432/nail_first_db
spring.datasource.username=postgres
spring.datasource.password=20190427
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

server.port=8080